#+title: Todo

* [X] player movement
CLOSED: [2022-07-15 Fri 16:34]
* [X] player looks at mouse
CLOSED: [2022-07-15 Fri 16:34]
* [X] player shoots at mouse
CLOSED: [2022-07-15 Fri 16:34]
* [X] remove bullets at some point
CLOSED: [2022-07-15 Fri 17:09]
* [X] fix: bullets collide with player when fired
CLOSED: [2022-07-15 Fri 17:09]
* [X] remove bg from 2x2 tilemap
CLOSED: [2022-07-15 Fri 17:26]
* [X] move tilemaps into our color scheme
CLOSED: [2022-07-15 Fri 17:26]
* [X] fire slower
CLOSED: [2022-07-15 Fri 17:30]
* [X] apply colorscheme to dice
CLOSED: [2022-07-15 Fri 17:42]
* [X] right click to 'roll' to change your side
CLOSED: [2022-07-15 Fri 18:20]
* [X] progression - unlock all the sides!
CLOSED: [2022-07-16 Sat 11:15]
that's the quick game
** level 1 - we're a zero
need to dodge the ones and get the ~sparkly 1~

you're side `one`
can shoot `ones`
rolling returns to 1
can only hit other `ones`

or do you lose the side you're showing when hit?

** level 2 -
* [X] reveal instructions in order, after the upgrade was collected
CLOSED: [2022-07-16 Sat 11:50]
* [X] HUD showing health (number of hearts?)
CLOSED: [2022-07-16 Sat 12:54]
* [X] HUD showing unlocked sides
CLOSED: [2022-07-16 Sat 12:54]
* SKIP enemies don't shoot a `none` dice
CLOSED: [2022-07-16 Sat 12:54]
* [X] lighting
CLOSED: [2022-07-16 Sat 15:11]
dark env
light points added
use colors from pallette
* [X] basic wrappers
CLOSED: [2022-07-16 Sat 22:43]
** [X] title/main menu
CLOSED: [2022-07-16 Sat 17:41]
** SKIP level select
CLOSED: [2022-07-16 Sat 17:41]
jazz music
** [X] splash image
CLOSED: [2022-07-16 Sat 17:41]
*** [X] splash image? maybe from the jam?
CLOSED: [2022-07-16 Sat 17:41]
** SKIP controls
CLOSED: [2022-07-16 Sat 19:48]
jazz music
** [X] pause menu
CLOSED: [2022-07-16 Sat 20:23]
jazz music
* [X] sounds, music
CLOSED: [2022-07-16 Sat 22:43]
jazz music on menus
** [X] firing bleep-pew
CLOSED: [2022-07-16 Sat 19:48]
** [X] enemy death
CLOSED: [2022-07-16 Sat 19:48]
** [X] main menu song
CLOSED: [2022-07-16 Sat 18:16]
* [X] credits
CLOSED: [2022-07-17 Sun 00:11]
* [X] win screen
CLOSED: [2022-07-17 Sun 00:11]
* [X] handle (game over)
CLOSED: [2022-07-17 Sun 08:02]
* more interesting
** [X] create dice-nine boss art
CLOSED: [2022-07-17 Sun 08:49]
** [X] bullet sides subtract from the enemy score
CLOSED: [2022-07-17 Sun 10:02]
** [ ] cloning - upgrades grant you a clone
** [ ] rolling changes your 'gun'
guns are just sets of sides (pips)
** [ ] more enemies
*** mini-boss
larger, rolls often
gotta knock off all of their colors
spews out/leaves behind normal enemies
shoots at-you
*** huge 100 boss
subtract from his score while fighting him
disappears around the level
*** fires-while-spinning
*** fires-at-you
*** firing at more interesting intervals
maybe based on their number?
*** not firing so lamely in all directions
** [ ] upgrades come to you when you're close enough
** [ ] upgrades beyond 6 mean - extra player!
** [ ] escort levels
guide presidice safely to the prom
** [ ] progression - rest of the upgrades, then clone-upgrades
play until you have 6, then you've unlocked the escort story line
** [ ] consider restoring the wall-collisions
* [ ] respawn upgrades and enemies after death
* [ ] in-level music
* [ ] fix broken 'death' sound
seems to only fire the first time?
* [ ] upgrade sound
* [ ] bump into wall sound
* [ ] add texture to bg image
* [ ] highlight the upgrades more
maybe just text that flashes/dances around it?
** shiny-glowy-directions to off/onscreen upgrade
** will need to support clone-mode too
** maybe should give extra lives?
* [ ] add a laugh track when you die/get hurt?
* [ ] background audio player to maintain song across pause, main, and credits
